<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Sha Tao (st3117), Jingqi Song (js5165), Yixuan Wang (yw3095), Ditian Li (dl3157), Boya Guo (bg2604)" />


<title>The Association of Smoking and the Risk of Developing Breast Cancer in the United States, Using NHANES 2011-16 Datasets</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">Abstract</a>
</li>
<li>
  <a href="Visualization.html">Visualization</a>
</li>
<li>
  <a href="Introduction.html">Who are we</a>
</li>
<li>
  <a href="https://github.com/st3117/final_project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">The Association of Smoking and the Risk of Developing Breast Cancer in the United States, Using NHANES 2011-16 Datasets</h1>
<h4 class="author"><em>Sha Tao (st3117), Jingqi Song (js5165), Yixuan Wang (yw3095), Ditian Li (dl3157), Boya Guo (bg2604)</em></h4>
<h4 class="date"><em>December 6, 2018</em></h4>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Breast cancer is the most commonly diagnosed cancer among American women. It is estimated that about 1 in 8 U.S women will develop invasive breast cancer over the course of lifetime. An inverse association between smoking and breast cancer survival rate has been reported by many studies. A history of cigarette smoking can significantly increase the risk of breast cancer. However, there is a limited number of prior literatures investigate the association of smoking and breast cancer at a population level using national survey data. To address this knowledge gap, we conduct this secondary data analysis study on the National Health and Nutrition Examination Survey (NHANES) from year 2011 to 2016 to see if there is a trend of smoking and breast cancer risk across years in the United States.</p>
</div>
<div id="related-work" class="section level2">
<h2>Related work</h2>
<p>Instruction from CDC website indicates smoking status as a risk factor that could be changed, which is the main effect of our study. We also find whether the subject is overweight, alcohol consumption as potential factors of from the website. Also, previous studies suggest household income and age at first live birth as 2 important predictors for breast cancer. Age and race are the two variables we need to adjust for in our models.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial Questions:</h2>
<p>Does racial/ethnic disparity present in the association of obesity and risk of breast cancer in the United States, when we controlling for age?</p>
<p>The key predictor of interest was established using the question on “have you smoked at least 100 cigarettes in your entire life”. The outcome of this study used the question “what kind of cancer was it”. Other covariates such as race, age, alcohol, overweight, income, and age at the first birth were identified based on literature review from Pubmed.</p>
</div>
<div id="initial-questions-1" class="section level2">
<h2>Initial Questions:</h2>
<p>Does the risk of breast cancer increases with heavy smoking in the United States, when we controlling for other covariates?</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p><strong>Source</strong> We used the Demographics and Questionnaire data files from the NHANES 2011-2016 datasets (<a href="https://wwwn.cdc.gov/nchs/nhanes/Default.aspx" class="uri">https://wwwn.cdc.gov/nchs/nhanes/Default.aspx</a>). NHANES is a nationally representative, multi-stage complex survey designed to assess the health and nutritional status of the non-institutionalized, civilian US population.</p>
<pre class="r"><code># readin csv file with url
files = read_csv(&quot;./data/file_link.csv&quot;)

# demographics
demo = 
  files %&gt;%  
  filter(str_detect(file_name, &quot;DEMO&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, gender = RIAGENDR, age = RIDAGEYR, race = RIDRETH3, edu = DMDEDUC3, 
         six_month = RIDEXMON, birth_country = DMDBORN4, marital_status = DMDMARTL, 
         pregancy_at_exam = RIDEXPRG, strata = SDMVSTRA, psu = SDMVPSU, weight = WTINT2YR) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;))),
         weight = 1/3 * weight) %&gt;% 
  select(id, year, gender:weight)

# cancer history
mcq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;MCQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, overweight = MCQ080, cancer_malignancy = MCQ220, cancer_code1 = MCQ230A, 
         cancer_code2 = MCQ230B, age_breast_cancer = MCQ240E, told_lose_weight = MCQ365A, 
         told_exercise = MCQ365B, told_reduce_fat = MCQ365D) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, overweight:told_reduce_fat)

# smoking history
smq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;SMQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, smoke_100 = SMQ020) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, smoke_100)

# hight / weight report
whq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;WHQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, self_height = WHD010, self_weight = WHD020, times_lost_ten_lb = WHQ225, 
         self_greaest_weight = WHD140, age_heaviest = WHQ150) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, self_height:age_heaviest)

# alcohol history
alq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;ALQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, alcohol = ALQ130) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, alcohol)
  
# reproduction
rhq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;RHQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, age_first_birth = RHD180) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, age_first_birth)

# incomce information
inq = 
  files %&gt;% 
  filter(str_detect(file_name, &quot;INQ&quot;)) %&gt;% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %&gt;% 
  unnest %&gt;% 
  select(file_name, id = SEQN, income = INDFMMPC) %&gt;% 
  mutate(year = as.factor(ifelse(str_detect(file_name, &quot;_G&quot;) == TRUE, &quot;2011-2012&quot;, 
                          ifelse(str_detect(file_name, &quot;_H&quot;) == TRUE, &quot;2013-2014&quot;, &quot;2015-2016&quot;)))) %&gt;% 
  select(id, year, income)</code></pre>
<p><strong>Scraping Method and Cleaning</strong></p>
<pre class="r"><code># replace &quot;refused&quot;&quot; and &quot;don&#39;t know&quot; data as missing 
nhanes = merge(demo, merge(alq, merge(inq, merge(mcq, merge(rhq, merge(smq, whq)))))) %&gt;% 
  replace_with_na(replace = list(birth_country = c(77, 99), marital_status = c(77, 99), overweight = c(7, 9),
                                 cancer_malignancy = c(7, 9), cancer_code1 = 99, age_breast_cancer = 99999,
                                 told_lose_weight = c(7, 9), told_exercise = c(7, 9), told_reduce_fat = c(7, 9),
                                 self_height = c(7777, 9999), self_weight = c(7777, 9999),
                                 times_lost_ten_lb = c(7, 9), self_greaest_weight = c(7777, 9999),
                                 age_heaviest = c(77777, 99999), smoke_100 = c(7, 9), alcohol = c(777, 999),
                                 income = c(7, 9), age_first_birth = c(777, 999)))
# tried replace_with_na_all() function but failed

# clean and choose the predictors and exposures
nhanes_model = 
  nhanes %&gt;% 
  mutate(breast_cancer = ifelse(cancer_code1 == 14 | cancer_code2 == 14, 1, 0),
         breast_cancer = as.factor(ifelse(is.na(breast_cancer), 0, breast_cancer)),
         race = ifelse(race == 1, &quot;Mexican&quot;,
                       ifelse(race == 2, &quot;Hispanic&quot;,
                              ifelse(race == 3, &quot;White&quot;,
                                     ifelse(race == 4, &quot;Black&quot;,
                                            ifelse(race == 6, &quot;Asian&quot;, &quot;Other&quot;))))),
         race = fct_relevel(as.factor(race), &quot;White&quot;),
         overweight = fct_relevel(as.factor(overweight), &#39;2&#39;),
         smoke_100 = fct_relevel(as.factor(smoke_100), &#39;2&#39;),
         income = fct_relevel(as.factor(income), &#39;2&#39;)) %&gt;% 
  filter(gender == 2) %&gt;% 
  select(id, year, age, race, breast_cancer, overweight, smoke_100, age_breast_cancer, alcohol, age_first_birth, 
         income, strata, psu, weight)</code></pre>
<pre class="r"><code>skimr::skim(nhanes_model)</code></pre>
<pre><code>## Skim summary statistics
##  n obs: 8920 
##  n variables: 14 
## 
## -- Variable type:factor -----------------------------------------------------------------------------------------------------------------
##       variable missing complete    n n_unique
##  breast_cancer       0     8920 8920        2
##         income     565     8355 8920        3
##     overweight       4     8916 8920        2
##           race       0     8920 8920        6
##      smoke_100     152     8768 8920        2
##           year       0     8920 8920        3
##                                  top_counts ordered
##                      0: 8674, 1: 246, NA: 0   FALSE
##          3: 3890, 1: 3306, 2: 1159, NA: 565   FALSE
##                     2: 5445, 1: 3471, NA: 4   FALSE
##  Whi: 3205, Bla: 2068, Mex: 1247, Asi: 1093   FALSE
##                   2: 5919, 1: 2849, NA: 152   FALSE
##      201: 3101, 201: 2976, 201: 2843, NA: 0   FALSE
## 
## -- Variable type:numeric ----------------------------------------------------------------------------------------------------------------
##           variable missing complete    n     mean       sd       p0
##                age       0     8920 8920    47.56    18.38    18   
##  age_breast_cancer    8676      244 8920    55.86    12.97    14   
##    age_first_birth    3885     5035 8920    22.2      4.93    14   
##            alcohol    4118     4802 8920     2.14     1.79     1   
##                 id       0     8920 8920 78315.31  9172.62 62164   
##                psu       0     8920 8920     1.53     0.55     1   
##             strata       0     8920 8920   111.26    12.94    90   
##             weight       0     8920 8920 13269.13 11657.91  1776.99
##       p25      p50      p75     p100     hist
##     32       47       62       80    &lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2586&gt;
##     47.75    56       65       80    &lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2582&gt;&lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2583&gt;
##     19       21       25       43    &lt;U+2583&gt;&lt;U+2587&gt;&lt;U+2583&gt;&lt;U+2583&gt;&lt;U+2582&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;
##      1        2        3       30    &lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;
##  69930.75 78955.5  86133    93702    &lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2585&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2587&gt;&lt;U+2587&gt;
##      1        2        2        3    &lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;
##    100      111      123      133    &lt;U+2587&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2586&gt;&lt;U+2587&gt;
##   5913.93  8639.98 15472.36 77918.61 &lt;U+2587&gt;&lt;U+2582&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2581&gt;</code></pre>
</div>
<div id="weighting-in-nhanes-dataset" class="section level2">
<h2>Weighting in NHANES Dataset</h2>
<p>Weights variables were created in NHANES dataset to analyze NHANES dataset to account for the multistage complex survey design. NHANES survey consists initial in-home interview, Mobile Examination Centers (MEC) examinations and follow-up questionnaires. The base weights were adjusted for nonresponse to the in-home interview when creating interview weights, and further adjusted for non-response to the MEC exam when creating exam weights. Therefore, to correctly analyze NHANES dataset, we need to consider the effects of weighting on our sample to make a better estimate for the population before we start our analysis.</p>
<p>To investigate the association between smoking and risk of breast cancer across racial/ethnic groups from 2011 to 2016, we pooled the Demographics (demo), Weight History (whq), Medical Conditions (mcq), Smoking History (smq), Alcohol (alq), and Income (inq) data files for each survey cycle using the urls. Then, we merged and tidied our data. We recoded “refused” (7 or 77 or 777) “don’t know” (9, 99, 999, 9999) responses as missing value.</p>
</div>
<div id="weighting-in-nhanes-dataset-1" class="section level2">
<h2>Weighting in NHANES Dataset</h2>
<p>Weights variables were created in NHANES dataset to analyze NHANES dataset to account for the complex survey design. NHANES survey consists initial in-home interview, Mobile Examination Centers (MEC) examinations and follow-up questionnaires. The base weights were adjusted for nonresponse to the in-home interview when creating interview weights, and further adjusted for non-response to the MEC exam when creating exam weights. Therefore, to correctly analyze NHANES dataset, we need to consider the effects of weighting on our sample to make a better estimate for the population before we start our analysis.</p>
<p>Based on the tutorial for National Health and Nutrition Examination Survey, we should select the weight of the smallest analysis subpopulation to produce estimates appropriately adjusted for survey non-response. Each NHANES survey cycle is divided into five sections labeled by collection method: Demographics, Dietary, Examination, Laboratory, and Questionnaire. This study only used variables from Demographics and Questionnaire (Weight History, Medical Conditions data files).</p>
<pre class="r"><code># Make Survey Design
design = svydesign(id = ~psu, strata = ~strata, data = nhanes_model, weights = ~weight, nest = TRUE)</code></pre>
<p>Since the Demographics and Questionnaire data were both collected as part of the household interview, the sample weight used for this study should be WTINT2YR, which is the full sample 2-year interview weight. The next step is to construct weights for combined NHANES survey cycles. For a 6-year data from 2011 to 2016, a weight should be constructed as ⅓ *WTINT2YR. We renamed variable WTINT2YR as ‘weight’ and divided ‘weight’ by 3 to represent the weight from 2011-2016 only using the household interview data.</p>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory analysis:</h2>
<p>Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.</p>
</div>
<div id="discussion-and-implication" class="section level2">
<h2>Discussion and Implication:</h2>
<ul>
<li>Planned analyses
<ul>
<li>Analyze the age onset of breast cancer across the total population, and the distribution of smoking incidences across racial/ethnic groups</li>
<li>Use logistic regression to investigate the association between smoking and breast cancer in each race/ethnic groups</li>
</ul></li>
<li>Visualizations
<ul>
<li>Boxplot of breast cancer incidences across racial/ethnic groups</li>
<li>Histogram of breast cancer incidences in each age groups</li>
<li>Scatter plot of breast cancer incidences in each racial/ethnic group across 6 years</li>
<li>Perform logistic regression</li>
</ul></li>
</ul>
<pre class="r"><code># proposed model 1, smoking as main effectr
model1 = svyglm(breast_cancer ~ age + race + smoke_100, family = &quot;binomial&quot;, design = design)

# null model 2, include only age and race 
model2 = svyglm(breast_cancer ~ age + race, family = &quot;binomial&quot;, design = design)

# full model 3, include all the variables mentioned in the reference
model3 = svyglm(breast_cancer ~ age + race + smoke_100 + overweight + alcohol + age_first_birth + income, family = &quot;binomial&quot;, design = design)

# comparison of AIC between 3 models
tibble(
  model = c(&quot;model1&quot;, &quot;model2&quot;, &quot;model3&quot;),
  AIC = c(summary(model1)$aic, summary(model2)$aic, summary(model3)$aic)) %&gt;% 
  knitr::kable(digit = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">model1</td>
<td align="right">1850.594</td>
</tr>
<tr class="even">
<td align="left">model2</td>
<td align="right">1853.784</td>
</tr>
<tr class="odd">
<td align="left">model3</td>
<td align="right">833.398</td>
</tr>
</tbody>
</table>
<pre class="r"><code># comparison between proposed model (model 1) and null model (model 2)
anova(model1, model2, method = &quot;Wald&quot;)</code></pre>
<pre><code>## Wald test for smoke_100
##  in svyglm(formula = breast_cancer ~ age + race + smoke_100, family = &quot;binomial&quot;, 
##     design = design)
## F =  3.201956  on  1  and  40  df: p= 0.081124</code></pre>
<pre class="r"><code># p-value &lt; 0.1, we can conclude that proposed mode is significantly better than null model

# comparison between proposed model (model 1) and null model (model 3)
anova(model1, model3, method = &quot;Wald&quot;)</code></pre>
<pre><code>## Wald test for overweight alcohol age_first_birth income
##  in svyglm(formula = breast_cancer ~ age + race + smoke_100 + overweight + 
##     alcohol + age_first_birth + income, family = &quot;binomial&quot;, 
##     design = design)
## F =  1.073669  on  5  and  35  df: p= 0.39167</code></pre>
<pre class="r"><code># p-value &gt; 0.1, we can conclude that proposed mode is similar to the full model</code></pre>
<p>The proposed model (model 1) with smoking as the main effect is significantly better than the null model at alpha = 0.1 level, while the proposed model is similar to the full model. Thus, it is reasonable to use the proposed model.</p>
<pre class="r"><code>broom::tidy(model1) %&gt;% 
  mutate(OR = exp(estimate),
         conf.low = exp(estimate - 1.645 * std.error),
         conf.high = exp(estimate + 1.645 * std.error)) %&gt;% 
  select(term, beta = estimate, p.value, OR, conf.low, conf.high) %&gt;% 
  knitr::kable(digit = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">beta</th>
<th align="right">p.value</th>
<th align="right">OR</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-7.696</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.001</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">0.071</td>
<td align="right">0.000</td>
<td align="right">1.073</td>
<td align="right">1.065</td>
<td align="right">1.082</td>
</tr>
<tr class="odd">
<td align="left">raceAsian</td>
<td align="right">-0.125</td>
<td align="right">0.681</td>
<td align="right">0.883</td>
<td align="right">0.538</td>
<td align="right">1.448</td>
</tr>
<tr class="even">
<td align="left">raceBlack</td>
<td align="right">-0.334</td>
<td align="right">0.088</td>
<td align="right">0.716</td>
<td align="right">0.523</td>
<td align="right">0.980</td>
</tr>
<tr class="odd">
<td align="left">raceHispanic</td>
<td align="right">0.092</td>
<td align="right">0.684</td>
<td align="right">1.096</td>
<td align="right">0.759</td>
<td align="right">1.584</td>
</tr>
<tr class="even">
<td align="left">raceMexican</td>
<td align="right">-0.473</td>
<td align="right">0.059</td>
<td align="right">0.623</td>
<td align="right">0.418</td>
<td align="right">0.929</td>
</tr>
<tr class="odd">
<td align="left">raceOther</td>
<td align="right">-0.332</td>
<td align="right">0.605</td>
<td align="right">0.718</td>
<td align="right">0.252</td>
<td align="right">2.045</td>
</tr>
<tr class="even">
<td align="left">smoke_1001</td>
<td align="right">0.358</td>
<td align="right">0.081</td>
<td align="right">1.431</td>
<td align="right">1.029</td>
<td align="right">1.988</td>
</tr>
</tbody>
</table>
<p>The odds of getting breast cancer among women who had smoked is 1.431 times the odds comparing to the ones who had not smoked controlling for age and race. The true odds ratio lies between 1.029 and 1.988.</p>
</div>
<div id="visualization" class="section level2">
<h2>Visualization</h2>
<p>Since we are using weight, strata and cluster data, which is not the same as the original data, we have to use the ‘svyplot’ to do the visualization</p>
<pre class="r"><code># Distribution of Age at Breast Cancer
svyhist(~nhanes_model$age_breast_cancer, breaks = c(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80), col = &quot;grey&quot;, design, main = &quot;Distribution of Age at Breast Cancer&quot;, xlab = &quot;Age at Breast Cancer&quot;)</code></pre>
<p><img src="final_project_files/figure-html/plots-1.png" width="672" /></p>
<pre class="r"><code># Distribution of Age at Breast Cancer Across Racial Groups
svyboxplot(age_breast_cancer ~ race, design, xlab = &quot;Race&quot;, ylab = &quot;Age at Breast Cancer&quot;,
           main = &quot;Distribution of Age at Breast Cancer Across Racial Groups&quot;)</code></pre>
<p><img src="final_project_files/figure-html/plots-2.png" width="672" /></p>
<pre class="r"><code># Distribution of Age at Breast Cancer Across Three Interviews
svyboxplot(age_breast_cancer ~ year, design, xlab = &quot;Interview Year&quot;, ylab = &quot;Age at Breast Cancer&quot;, 
           main = &quot;Distribution of Age at Breast Cancer Across Three Interviews&quot;)</code></pre>
<p><img src="final_project_files/figure-html/plots-3.png" width="672" /></p>
<ul>
<li>The histogram plot “Distribution of Age at Breast Cancer”showed that women within 50 - 60 age group have the highest risk of getting breast cancer than the other age group.</li>
<li>The boxplot “Distribution of Age at Breast Cancer Across Racial Groups” showed that Asian and ‘Other’ race group have relatively earilier breast cancer onset, while White and Mexican American have later breast cancer onset.</li>
<li>The boxplot “Distribution of Age at Breast Cancer Across Three Interviews” showed that the age of women getting breast cancer are similar in three interview period.</li>
</ul>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<ol style="list-style-type: decimal">
<li>Bandera, Elisa V., et al. “Racial and Ethnic Disparities in the Impact of Obesity on Breast Cancer Risk and Survival: A Global Perspective–.” <em>Advances in Nutrition 6.6 (2015): 803-819.</em> <a href="https://academic.oup.com/advances/article/6/6/803/4555151" class="uri">https://academic.oup.com/advances/article/6/6/803/4555151</a></li>
<li>Chlebowski, Rowan T., et al. “Ethnicity and breast cancer: factors influencing differences in incidence and outcome.” <em>Journal of the National Cancer Institute 97.6 (2005): 439-448.</em> <a href="https://academic.oup.com/jnci/article/97/6/439/2544155" class="uri">https://academic.oup.com/jnci/article/97/6/439/2544155</a></li>
<li>Picon‐Ruiz, Manuel, et al. “smoking and adverse breast cancer risk and outcome: mechanistic insights and strategies for intervention.” <em>CA: a cancer journal for clinicians 67.5 (2017): 378-397.</em> <a href="https://onlinelibrary.wiley.com/doi/full/10.3322/caac.21405" class="uri">https://onlinelibrary.wiley.com/doi/full/10.3322/caac.21405</a></li>
<li>Module 3: Weighting. National Center for Health Statistics. Centers for Disease Control and Prevention. Retrieved from <a href="https://wwwn.cdc.gov/nchs/nhanes/tutorials/Module3.aspx" class="uri">https://wwwn.cdc.gov/nchs/nhanes/tutorials/Module3.aspx</a></li>
<li>Kispert, S., &amp; McHowat, J. (2017). Recent insights into cigarette smoking as a lifestyle risk factor for breast cancer. Breast Cancer: Targets and Therapy, 9, 127.</li>
</ol>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
