---
title: "test"
author: Sha Tao (st3117), Jingqi Song (js5165), Yixuan Wang (yw3095),  Ditian Li (dl3157), Boya Guo (bg2604)
date: "November 8, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(rlist)
library(naniar)
library(rvest)
library(httr)
library(survey)

```

## Load 6 years NHANES data from XPT files

```{r}

files = read_csv("./data/file_link.csv")

demo = 
  files %>%  
  filter(str_detect(file_name, "DEMO")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, gender = RIAGENDR, age = RIDAGEYR, race = RIDRETH3, edu = DMDEDUC3, 
         six_month = RIDEXMON, birth_country = DMDBORN4, marital_status = DMDMARTL, 
         pregancy_at_exam = RIDEXPRG, strata = SDMVSTRA, psu = SDMVPSU, weight = WTINT2YR) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016"))),
         weight = 1/3 * weight) %>% 
  select(id, year, gender:weight)

mcq = 
  files %>% 
  filter(str_detect(file_name, "MCQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, overweight = MCQ080, cancer_malignancy = MCQ220, cancer_code1 = MCQ230A, 
         cancer_code2 = MCQ230B, age_breast_cancer = MCQ240E, told_lose_weight = MCQ365A, 
         told_exercise = MCQ365B, told_reduce_fat = MCQ365D) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, overweight:told_reduce_fat)

smq = 
  files %>% 
  filter(str_detect(file_name, "SMQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, smoke_100 = SMQ020) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, smoke_100)

whq = 
  files %>% 
  filter(str_detect(file_name, "WHQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, self_height = WHD010, self_weight = WHD020, times_lost_ten_lb = WHQ225, 
         self_greaest_weight = WHD140, age_heaviest = WHQ150) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, self_height:age_heaviest)
  
alq = 
  files %>% 
  filter(str_detect(file_name, "ALQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, alcohol = ALQ110) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, alcohol)
  

rhq = 
  files %>% 
  filter(str_detect(file_name, "RHQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, age_first_birth = RHD180) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, age_first_birth)

inq = 
  files %>% 
  filter(str_detect(file_name, "INQ")) %>% 
  mutate(map(.x = file_link, ~read_xpt(.x))) %>% 
  unnest %>% 
  select(file_name, id = SEQN, income = INDFMMPC) %>% 
  mutate(year = as.factor(ifelse(str_detect(file_name, "_G") == TRUE, "2011-2012", 
                          ifelse(str_detect(file_name, "_H") == TRUE, "2013-2014", "2015-2016")))) %>% 
  select(id, year, income)


```


## Clean Data

```{r clean_data}

# replce 
nhanes = merge(demo, merge(alq, merge(inq, merge(mcq, merge(rhq, merge(smq, whq)))))) %>% 
  replace_with_na(replace = list(birth_country = c(77, 99), marital_status = c(77, 99), overweight = c(7, 9),
                                 cancer_malignancy = c(7, 9), cancer_code1 = 99, age_breast_cancer = 99999,
                                 told_lose_weight = c(7, 9), told_exercise = c(7, 9), told_reduce_fat = c(7, 9),
                                 self_height = c(7777, 9999), self_weight = c(7777, 9999),
                                 times_lost_ten_lb = c(7, 9), self_greaest_weight = c(7777, 9999),
                                 age_heaviest = c(77777, 99999), smoke_100 = c(7, 9), alcohol = c(7, 9),
                                 income = c(7, 9), age_first_birth = c(777, 999)))
# tried replace_with_na_all() function but failed

# clean and choose the predictors and exposures
nhanes_model = 
  nhanes %>% 
  mutate(breast_cancer = ifelse(cancer_code1 == 14 | cancer_code2 == 14, 1, 0),
         breast_cancer = as.factor(ifelse(is.na(breast_cancer), 0, breast_cancer)),
         race = fct_relevel(as.factor(race), '3'),
         overweight = fct_relevel(as.factor(overweight), '2'),
         smoke_100 = fct_relevel(as.factor(smoke_100), '2'),
         alcohol = fct_relevel(as.factor(alcohol), '2'),
         income = fct_relevel(as.factor(income), '2')) %>% 
  filter(gender == 2) %>% 
  select(id, year, age, race, breast_cancer, overweight, smoke_100, age_breast_cancer, alcohol, age_first_birth, 
         income, strata, psu, weight)

skimr::skim(nhanes_model)

nhanes_model %>% 
  filter(breast_cancer == 1) %>% 
  View()

```

## Survey Data Design

```{r}

# Make Survey Design
design = svydesign(id = ~psu, strata = ~strata, data = test_df, weights = ~weight, nest = TRUE)

```

## Simple Statistics

```{r}

svymean(~nhanes_model$age_breast_cancer, design = design, na.rm = TRUE)
mean(nhanes_model$age_breast_cancer, na.rm = TRUE)

test_df %>% filter(breast_cancer == 1) %>% View()
levels(test_df$smoke_100)

```

## Test logistic and survey logistic models

```{r test_logistic}

model1 = svyglm(breast_cancer ~ age + race + overweight + smoke_100, family = "binomial", design = design)
broom::tidy(model1)
summary(model1)
broom::glance(model1)
AIC(model1)



model1 = glm(formula = breast_cancer ~ age + race + overweight + smoke_100, family = "binomial", data = test_df)
broom::tidy(model1)




```

```{r}

nhanes %>% 
  filter(cancer_code1 == 14 | cancer_code2 == 14) %>% 
  mutate(race = as.factor(race)) %>%
  group_by(race) %>% 
  count() %>% 
  ggplot(aes(x = race, y = n)) +
    geom_point()

nhanes_model %>% 
  ggplot(aes(x = age_breast_cancer)) + 
    geom_histogram() +
    labs(
    title = "Distribution of Age at Breast Cancer",
    x = "Age at Breast Cancer"
    )

svyhist(~nhanes_model$age_breast_cancer, breaks = , design, main = "Distribution of Age at Breast Cancer")



nhanes %>% 
  filter(cancer_code1 == 14 | cancer_code2 == 14) %>% 
  ggplot(aes(x = age)) +
    geom_histogram()

nhanes %>% 
  filter(cancer_code1 == 14 | cancer_code2 == 14) %>% 
  ggplot(aes(x = year, y = age)) +
    geom_boxplot()
```



