---
title: "Problem2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(p8105.datasets)
library(plotly) 
```
```{r dataset, include=FALSE}
hw4 = ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(prcp = as.numeric(prcp),
         tmax = as.numeric(tmax),
         tmin = as.numeric(tmin),
         prcp = prcp / 10,
         tmin = tmin / 10,
         tmax = tmax / 10) %>% 
  filter(year == 2008)
```


Column {data-width=550}
-----------------------------------------------------------------------

### Chart A: The Precipitation in Year 2008

```{r}
hw4 %>%
  plot_ly(x = ~month, y = ~day, z = ~prcp,
          color = ~month)
```


Column {data-width=450}
-----------------------------------------------------------------------

### Chart B: The Sum of Snowfall by Month in Year 2008.

```{r}
hw4 %>%
  select(month, day, snow) %>%
  filter(!is.na(snow)) %>% 
  group_by(month) %>% 
  summarize(sum_snow = sum(snow)) %>%
  mutate(sum_snow = sum_snow/1000) %>% 
  plot_ly(x = ~month, 
          y = ~sum_snow, 
          color = ~month, 
          type = "bar",
          colors = "Set2")
```

### Chart C: The Mean Maximum Temperature and Mean Minimum Temperature by Month in Year 2008.

```{r}
hw4 %>%
  select(month, day, tmax, tmin) %>%
  filter(!is.na(tmax), !is.na(tmin)) %>%
  group_by(month) %>% 
  summarise(mean_tmax = mean(tmax),
            mean_tmin = mean(tmin)) %>% 
  plot_ly(x = ~month, 
          y = ~mean_tmax,
          name = "mean_tmax",
          type = "scatter", 
          mode = "lines",
          alpha = 0.5) %>% 
  add_trace(y = ~mean_tmin, name = "mean_tmin", mode = 'lines+markers')
```

